CC=g++
CFLAGS=-O2 -std=gnu++11
LIBS=-mwindows -lmingw32 -lSDL2main -lSDL2 -lSDL2_ttf -lSDL2_image -lSDL2_mixer

all: bin/treewatcher.exe

bin/treewatcher.exe: src/main.cpp
	$(CC) src/main.cpp $(CFLAGS) $(LIBS) -o bin/treewatcher.exe
